### ISSUE TITLE
Rejestracja użytkownika - wysłanie emaila powitalnego

### ISSUE THREAD

**Issue by ghost** [mateo9x/hrSystem#13]
Jako właściciel projektu chcę, żeby:

po pomyślnym zarejestrowaniu użytkownika został wysłany powitalny email do właściciela nowego konta o treści:

Temat: "HR System - Rejestracja konta"

Treść: 
"Witaj [imie] [nazwisko] ! 

Twoje konto w portalu HR System zostało pomyślnie zarejestrowane.
Poproś przełożonego o nadanie uprawnień w celu możliwości logowania do aplikacji.

Miłego dnia :)"

W celu wykonania zadania należy wykonać zmiany analogicznie do logiki resetu hasła.

Klasy do zmodyfikowania: 
- MailService (dodanie nowej metody analogicznie do "sendResetPasswordToken()")
- MailServiceImpl (dodanie nowej metody analogicznie do "sendResetPasswordToken()")
- UserServiceImpl (wpięcie się w metodę "save()" przed returnem końcowym - należy w lini 36 wywołać logikę wysyłki e-mail z klasy mailService)

**Comment by Bobus123** [comment]
Mail powitalny działa, pozdrawiam
