### ISSUE TITLE
Dodanie "maski" dla kodu pocztowego i nr tel

### ISSUE THREAD

**Issue by ghost** [mateo9x/hrSystem#14]
Jako właściciel projektu chcę, żeby:

Podczas wypełniania formularza rejestracji, a dokładniej pola z kodem pocztowym i nr telefonu aplikacja automatycznie dodawała "-" (kod pocztowy) i " " (tel co 3 cyfry) przy wypełnianiu w zakładce Rejestracja i Użytkownicy. Dodatkowo powinny być odpowiednie walidacje na te pola (blokowanie możliwości zapisu)

W tym celu należy:

- zainstalować ngx-mask (terminal i komenda "npm install --save ngx-mask" w folderze "angular")
- dodać zależności w klasie AppModule (Angular)
![image](https://user-images.githubusercontent.com/61753245/212571708-e28ac1ea-8915-4a85-816b-1b9d4054a0bb.png)
- zmodyfikować szablon sign-up.component.html
![image](https://user-images.githubusercontent.com/61753245/212571740-b5a30719-b0fa-4384-8623-ee4defc76541.png)

Dokumentacja biblioteki:
https://www.npmjs.com/package/ngx-mask

**Comment by Bobus123** [comment]
Zostala nalozona maska na kod pocztowy oraz telefon w sekcji rejstracji i edycji, usuniete patterny i walidacje poniewaz maska przejela ich zadanie
