### ISSUE TITLE
Brak 'X' przy probie resetowania hasła

### ISSUE THREAD

**Issue by Bobus123** [mateo9x/hrSystem#22]
Brak 'x' aby bez problemu wyjść z opcji resetowania hasła lub możliwość wyjścia klikając na tło (do zrobienia)

**Comment by mateo9x** [comment]
Dobry pomysł. Dodatkowo dodałbym takiego "X" również w zakładce w której resetujemy hasło poprzez wprowadzenie adresu e-mail. Oba komponenty są bardzo podobne stylistycznie, wiec należy umieścić to w obu miejscach. Natomiast w zakładce rejestrowania użytkownika na gorze można dodać ikonę "zawrócone strzałki", która po kliknięciu cofnie nas do ekranu logowania do aplikacji.

![image](https://user-images.githubusercontent.com/122756875/212769048-ee0da431-790c-4ed7-950a-8fe53f350068.png)

**Comment by mateo9x** [comment]
Poszedłbym bardziej w stronę eventa html (onBackspace) dla formularza rejestracji i (onEscape) dla ekranu logowania, resetu hasła (ekran wprowadzenia e-mail) i resetu hasła (ekran wprowadzania nowego hasła).
