### ISSUE TITLE
Brak walidacji w zakladce Uzytkownicy

### ISSUE THREAD

**Issue by mateo9x** [mateo9x/hrSystem#25]
W zakładce Administracja -> Użytkownicy -> Edytuj użytkownika brakuje walidacji na pola analogicznie do zakładki rejestracji użytkownika. Jako użytkownik chce aby walidacje na pola działały analogicznie do zakładki rejestracji.

Żeby mieć dostęp do zakładek należy zalogować się do aplikacji przy pomocy admin@admin.com : admin lub swojemu użytkownikowi nadać rolę np: 'ROLE_ADMIN'

![image](https://user-images.githubusercontent.com/122756875/213269976-97c9dbe9-ddcd-42ef-a3b4-7d87fc09f07a.png)

**Comment by Bobus123** [comment]
Walidacje dodane, jednak pewnie trzeba bedzię poprawić zeby pola sie nie rozjeżdżały. Pozdrawiam

**Comment by mateo9x** [comment]
> Walidacje dodane, jednak pewnie trzeba bedzię poprawić zeby pola sie nie rozjeżdżały. Pozdrawiam

Nie merguejmy jeśli coś nie działa dobrze, zatem w ramach zadania powinny cssy zostać poprawione.

**Comment by mateo9x** [comment]
OK, zrobie.
