### ISSUE TITLE
Formularz rejestracji - przycisk "Wyczyść"

### ISSUE THREAD

**Issue by mateo9x** [mateo9x/hrSystem#35]
Na w pełni wypełnionym formularzu rejestracji nowego użytkownika, po kliknięciu przycisk "Wyczyść" nie wszystkie dane zostają wyczyszczone (tj. na obrazku).

![image](https://user-images.githubusercontent.com/122756875/213917732-1a3dee75-7092-44fe-88e7-788f48043d05.png)

Prośba o poprawę funkcjonowanie tego przycisku, aby wszystkie dane były czyszczone.

**Comment by Bobus123** [comment]
Done.
