### ISSUE TITLE
Wnioski urlopowe - nowy wniosek

### ISSUE THREAD

**Issue by mateo9x** [mateo9x/hrSystem#39]
W oknie dialogowym tworzenia nowego wniosku urlopowego placeholder dla obu dat (data od i data do) jest taki sam. W drugim placeholderze powinna być wartość "Wybierz datę do" zamiast "Wybierz datę od".

Prośba o poprawkę.

![image](https://user-images.githubusercontent.com/122756875/213942419-85666d96-5ca5-44f9-bc4d-27de61fcab9b.png)

**Comment by Bobus123** [comment]
Poprawione
