### ISSUE TITLE
Wnioski urlopowe - nowy wniosek

### ISSUE THREAD

**Issue by mateo9x** [mateo9x/hrSystem#40]
W oknie dialogowym nowego wniosku urlopowego typy urlopów do wybrania nie są posortowane alfabetycznie rosnąco.

Prośba o posortowanie wniosków rosnąco (Spring/Java - backend).

![image](https://user-images.githubusercontent.com/122756875/213942476-99e4bb95-5764-4980-82a8-79a08dd8357d.png)

**Comment by Bobus123** [comment]
Sortowanie zrobione.
