### ISSUE TITLE
Formularz rejestracji i zakładka Użytkownicy - patterny dla imienia i nazwiska

### ISSUE THREAD

**Issue by mateo9x** [mateo9x/hrSystem#52]
Chcę, żeby imie i nazwisko w zakładce Rejesracji jak i Administracja -> Użytkownicy wymagała podanie pierwszej litery imienia i nazwiska z duzej litery, w innym wypadku ma blokować guzik "Zapisz"

**Comment by mateo9x** [comment]
Czy to zadanie jest skończone @Bobus123  widnieje jako otwarte?

**Comment by Bobus123** [comment]
Zrobione
