### ISSUE TITLE
Widok rejestracji - brak wszystkich pól + walidatory

### ISSUE THREAD

**Issue by ghost** [mateo9x/hrSystem#6]
![image](https://user-images.githubusercontent.com/61753245/212548048-581b161c-e7c0-44cc-aa07-c7d21ab4d2e6.png)

W widoku rejestracji nie ma wszystkich pól do uzupełnienia względem bazy danych. 
W pierwszej kolejności istniejące inputy należy zmienić na komponenty Angular Material.

Następnie należy wprowadzić input'y dla:

- pesel
- kodpocztowy
- numer_telefonu

Następnie należy uwzględnić walidatory, które sa nałożone w backendzie na poszczególne pola (klasa User - src/main/java/domain/User.java)

**Comment by Bobus123** [comment]
Zadanie wykonane

**Comment by Bobus123** [comment]
Zadanie wykonane

**Comment by mateo9x** [comment]
@Bobus123  Po wykonanej implementacji występują błędy w formularzu rejestracji:

1.  Komunikat potwierdzenia hasła jest w środku znacznika <input> a nie poza nim tak jak w reszcie formularzy
![image](https://user-images.githubusercontent.com/122756875/212724851-f382b6b4-8ac4-4f74-9432-8bac81a79636.png)

2. Numer telefonu jest polem wymaganym, a nie powinien być (znacznik 'required')
![image](https://user-images.githubusercontent.com/122756875/212725039-4c1448a0-868a-4fd2-babe-ed7b0326cf5d.png)

**Comment by Bobus123** [comment]
Poprawione
